### ISSUE TITLE
Using the plugin stops PyCharm from hitting breakpoints.

### ISSUE THREAD

**Issue by morganthrapp** [pytest-dev/pytest-cov#131] opened 2016-09-02 14:39 UTC
System Details:

python 3.5.1
pytest 3.0.2
pytest-cov 2.3.1
PyCharm Community Edition 2016.2.2
Build #PC-162.1812.1, built on August 16, 2016
JRE: 1.8.0_76-release-b216 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

MCVE:

main.py

```
def foo():
    x = 10
    return x
```

test.py

```
import main

def test_foo():
    assert main.foo() == 10
```

Create a new project in PyCharm with those two files and create a new test config with the following options `--cov=. --cov-report term-missing -rw -vv`. Set a breakpoint on any line of code and hit debug.

Expected result:
The breakpoints work.

Actual result:
The breakpoints don't work.

If you remove the options, it hits the breakpoints fine.

**Comment by ionelmc** [comment] 2016-09-02 15:03
The coverage module and pycharm's debugger use the same tracing api (`sys.settrace`) - they don't work together. Either of those could support running the other tracer ... you should ask about it in their respective bugtrackers.

What pytest-cov could do is automatically disable itself if it detects an active pycharm tracer - but I'm not sure what's the point of having it.

**Comment by morganthrapp** [comment] 2016-09-02 15:06
There's an open issue in PyCharm's bug tracker. I just wasn't clear if this was something that could be fixed in the plugin or if it needed to be fixed by PyCharm/coverage.

I wouldn't mind having it disable itself if there's an active breakpoint, because PyCharm doesn't currently retain options if you uncheck the "use options" check box. This would at least save me from having to re-add the options after each time that I need to debug a test case.

However, I understand where that might be unexpected behaviour. Would you be open to it being a switched argument?

**Comment by ionelmc** [comment] 2016-09-02 15:36
What do you mean `switched argument`? Give some examples to be clear.

**Comment by nickmeet** [comment] 2016-09-02 15:42
Hi all,

I have opened the following ticket to PyCharm.
https://youtrack.jetbrains.com/issue/PY-20186

@ionelmc I guess @morganthrapp is asking you to make it configurable.

**Comment by morganthrapp** [comment] 2016-09-02 16:09
@nickmeet Yeah, thanks. That's exactly what I meant. I meant adding something like `--stop-on-breakpoint`. That way you don't break any existing workflows.

**Comment by nickmeet** [comment] 2016-09-05 09:01
@ionelmc as PyCharm said that they won't do anything, can you do something? If not, we can close this ticket by saying that PyCharm does not support debugging when coverage is enabled.

**Comment by ionelmc** [comment] 2016-09-05 10:22
I would like to understand first what's the problem with removing the `--cov` option when you run the tests in debug mode.

**Comment by RonnyPfannschmidt** [comment] 2016-09-05 12:27
i think this one should be closed as "working as intended, sys.settrace is mutally exclusive, the user has to pick one"

**Comment by nickmeet** [comment] 2016-09-05 21:57
Yeap

**Comment by kozmaz87** [comment] 2016-09-16 12:11
It is not a good idea for us having to remove the --cov option as that is in most cases in the pytest.ini file and committed to the repository. I would personally like to see a flag --no-cov, not just the otherwise very useful --no-cov-on-fail. In this case my pycharm launch configuration could specify the --no-cov flag so others would still get coverage for just hitting py.test but those of us using pycharm could use this flag instead.

**Comment by ionelmc** [comment] 2016-09-16 12:15
Some notes here:

* `--no-cov-on-fail` is not possible to implement (we can't know if test fails before test runs)
* `--no-cov` is implementable. However it will need to have precedence over everything. This means that if your coworkers sticks that into `pytest.ini` and you don't notice it you'll be wondering for hours about why coverage don't run regardless of how many combinations of `--cov` you add on command line.  Is this acceptable?

**Comment by RonnyPfannschmidt** [comment] 2016-09-16 12:33
@ionelmc how about `--clear-cov` or `--reset-cov` that will clear that list and enable people to turn it of (ideally used as last argument) but may also be used to clear `addopts` and set own ones)

**Comment by ionelmc** [comment] 2016-09-16 12:39
That looks even more confusing, hard to predict how it will work given many sources of options.

Perhaps `--no-cov` could work reasonably well, if we add specific warnings in output to make it clear what is going on. However, I'm not sure but I suspect that test runner in pycharm don't make it easy to see stdout/stderr output easily. Thus we haven't solved anything as we're aiming to improve usability in pycharm.

**Comment by kozmaz87** [comment] 2016-09-16 12:39
@ionelmc --no-cov-on-fail is implemented btw. I am using it fairly often. but I think what you mean is yes it collects coverage data it just won't spend time creating a report and that is good so but in our case this breaks pycharm. So the --no-cov flag that switches off stuff would be ok... @RonnyPfannschmidt would --reset-cov do the trick?

**Comment by kozmaz87** [comment] 2016-09-16 12:40
@ionelmc Also pycharm's test pytest runner completely ignores the targets set in pytest.ini. So who knows what else it chooses to ignore.

**Comment by ionelmc** [comment] 2016-09-16 12:46
Then I don't have a reasonable proposal here. I don't even run tests with pycharm. @morganthrapp or @nickmeet please give input here.

**Comment by kozmaz87** [comment] 2016-09-16 12:56
@ionelmc I think your proposal was ok. What did I say that confused you? pycharm is choosey what it takes from pytest.ini and what it chooses to ignore. The --cov related addopts are there but for instance even if I have testpaths that is overridden with whatever singular target one sets in pycharm. So my BDD tests are in different place than my unit tests I ended up with 2 launchconfigs. But all this story is sidetrack and just random interesting detail. The main thing is that --no-cov and a clear message stating that --no-cov was specified so coverage is turned off is a good idea. In that case the user can go and check all the crazy places they may have flags set.

**Comment by morganthrapp** [comment] 2016-09-16 13:15
I would be okay with `--no-cov`. My main complaint (and this is mostly a PyCharm bug), is that if you uncheck the "Use Options" checkbox in the run config clears my config. Appending/removing `--no-cov` is much quicker/easier than re adding the entire config.

**Comment by ionelmc** [comment] 2016-09-16 13:22
@morganthrapp so what do you have to say about https://github.com/pytest-dev/pytest-cov/issues/131#issuecomment-247590160 then?

**Comment by morganthrapp** [comment] 2016-09-16 13:24
Sounds good to me. PyCharm seems to be good about exposing stdout during test runs, at least based on the fact that `print` works without issue.

**Comment by kozmaz87** [comment] 2016-10-03 14:50
Is there any update on this one? Is someone working on a pull request? If not I may find the time to get down and do it but I do not want to introduce redundant effort if someone is already in progress with this...

**Comment by nickmeet** [comment] 2016-10-03 15:59
I would like to have this configurable even if it is used only by a few persons (IDE guys like me...) but I understand that such a pull request won't be accepted, so good luck...

**Comment by kozmaz87** [comment] 2016-10-03 16:08
To me it seemed the opposite. It looked like some people who answered this ended up having no real problem with the --no-cov proposal but some of the ppl. asked did not provide feedback. It seems to me this ticket will be stuck in a limbo phase unless we get this through :)

If they decide that it is PyCharm who should detect the cov plugin and strip the all their parameters when they load up the tests in debug mode then let's get the ticket back to them and suggest that solution.

**Comment by ionelmc** [comment] 2016-10-03 17:19
@kozmaz87 feel free to implement `--no-cov` in a PR.


I wonder if it's possible to disallow setting `--no-cov` in config files (to avoid pitfall described in https://github.com/pytest-dev/pytest-cov/issues/131#issuecomment-247590160). @RonnyPfannschmidt any ideas? It's it's not possible I don't mind, just a nice to have.

**Comment by ionelmc** [comment] 2017-10-28 04:13
Huh. Looks like I forgot to close this (https://github.com/pytest-dev/pytest-cov/pull/135).

**Closed by ionelmc** 2017-10-28 04:13 UTC
