### ISSUE TITLE
Coverage is not measured with Python 3.7.0

### ISSUE THREAD

**Issue by volans-** [pytest-dev/pytest-cov#215] opened 2018-07-26 09:54 UTC
I've noticed that `pytest-cov` doesn't report properly the coverage with Python 3.7.0. Here a simple repro:

### Directory structure
```
|-- foo
|   |-- __init__.py
|   `-- bar.py
`-- tests
    |-- __init__.py
    `-- test_baz.py
```

### Files content

All `__init__.py` files are empty.
#### `bar.py`
```
def baz():
    print('baz')
```

#### `test_baz.py`
```
from foo import bar


def test_foo():
    bar.baz()
```

### `pip freeze` for both Python 3.6.5 and 3.7.0 environments
```
$ pip freeze
atomicwrites==1.1.5
attrs==18.1.0
coverage==4.5.1
more-itertools==4.2.0
pluggy==0.6.0
py==1.5.4
pytest==3.6.3
pytest-cov==2.5.1
six==1.11.0
```

### Test results with Python 3.6.5 (correct result)
```
$ py.test -p no:logging --strict --cov-report=term-missing --cov=foo tests
=========================================== test session starts ============================================
platform darwin -- Python 3.6.5, pytest-3.6.3, py-1.5.4, pluggy-0.6.0
rootdir: /private/tmp/foo, inifile:
plugins: cov-2.5.1
collected 1 item

tests/test_baz.py .                                                                                  [100%]

---------- coverage: platform darwin, python 3.6.5-final-0 -----------
Name              Stmts   Miss  Cover   Missing
-----------------------------------------------
foo/__init__.py       0      0   100%
foo/bar.py            2      0   100%
-----------------------------------------------
TOTAL                 2      0   100%


========================================= 1 passed in 0.03 seconds =========================================
```

### Test results with Python 3.7.0 (incorrect result)
```
$ py.test -p no:logging --strict --cov-report=term-missing --cov=foo tests
=========================================== test session starts ============================================
platform darwin -- Python 3.7.0, pytest-3.6.3, py-1.5.4, pluggy-0.6.0
rootdir: /private/tmp/foo, inifile:
plugins: cov-2.5.1
collected 1 item

tests/test_baz.py .                                                                                  [100%]

---------- coverage: platform darwin, python 3.7.0-final-0 -----------
Name              Stmts   Miss  Cover   Missing
-----------------------------------------------
foo/__init__.py       0      0   100%
foo/bar.py            2      2     0%   1-2
-----------------------------------------------
TOTAL                 2      2     0%


========================================= 1 passed in 0.03 seconds =========================================
```

**Comment by ionelmc** [comment] 2018-08-08 18:10
I can't seem to reproduce your problem. I get this:
```
platform linux -- Python 3.7.0, pytest-3.6.4, py-1.5.4, pluggy-0.7.1
rootdir: /home/ionel/osp/pytest-cov, inifile: setup.cfg
plugins: xdist-1.22.5, forked-0.2, cov-2.5.1
collected 1 item

tests/test_baz.py .                                                                                                                                                  [100%]

----------- coverage: platform linux, python 3.7.0-final-0 -----------
Name              Stmts   Miss  Cover   Missing
-----------------------------------------------
foo/__init__.py       0      0   100%
foo/bar.py            2      0   100%
-----------------------------------------------
TOTAL                 2      0   100%
```

Perhaps you have other issues with your project layout (eg: your code is imported from site-packages not from cwd).

**Comment by anarcat** [comment] 2018-10-18 20:49
i get a [reproducible crash](https://gitlab.com/anarcat/feed2exec/-/jobs/109858660) when testing [feed2exec](https://gitlab.com/anarcat/feed2exec) in python 3.6 and 3.7 with cov 2.6, which i do not get in python 3.5:

```
INTERNALERROR> coverage.misc.CoverageException: Couldn't use data file '/home/anarcat/src/feed2exec/.coverage': UNIQUE constraint failed: file.path
```

i wonder if this could be something with changes in the sqlite3 standard library?

or is that a completely different bug I should file separately?

**Comment by blueyed** [comment] 2018-10-20 08:15
@anarcat 
Looks like a separate issue and like you are using coveragepy 5 (alpha) already (since it appears to use a SQLite DB instead of a JSON file for storage).
And after all it might be a bug with coveragepy then, since it appears to not handle the unique constraint on the DB correctly itself.

**Comment by anarcat** [comment] 2018-10-22 14:01
indeed, this looks like https://github.com/nedbat/coveragepy/issues/716 - thanks @blueyed !

**Comment by blueyed** [comment] 2018-10-23 13:16
Closing this for now (not reproducible).
@volans- 
Please provide more information in case this is still an issue for you.

**Closed by blueyed** 2018-10-23 13:16 UTC

**Comment by funkyfuture** [comment] 2019-08-31 13:24
fwiw, i'm currently experiencing the same with Python 3.8 (compared to 3.7).

**Comment by ElPincheTopo** [comment] 2019-10-22 22:27
I have the same issue as @funkyfuture . This is the output of the code coverage for the same code, using the same libraries in the 2 versions:

Python 3.7.4, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
 Name | Stmts | Miss | Branch | BrPart | Cover
------|-------|------|--------|--------|-------
 5078 | 511 | 1251 | 132 | 87%


 Name | Stmts | Miss | Branch | BrPart | Cover
------|-------|------|--------|--------|-------
 TOTAL | 7981 | 3737 | 1482 | 588 | 53%

 245 passed, 36 warnings

 Name | Stmts | Miss | Branch | BrPart | Cover
5078 | 511 | 1251 | 132 | 87%

**Comment by nedbat** [comment] 2019-10-25 23:56
@ElPincheTopo has written https://github.com/nedbat/coveragepy/issues/861 about this.
