### ISSUE TITLE
pytest-cov fails on travis

### ISSUE THREAD

**Issue by jgirardet** [pytest-dev/pytest-cov#196] opened 2018-03-31 20:35 UTC
Hellor,
Everything goeas, great, all test passes and then I have this message :
``` log

1.89s$ make test-coverage
pipenv run py.test  --cov pythonthesorimed --cov-report term-missing --cov-report html
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
rootdir: /home/travis/build/jgirardet/pythonthesorimed, inifile: pytest.ini
plugins: timeit-0.3.0, pythonpath-0.7.2, cov-2.5.1
collected 34 items                                                             
run-last-failure: run all (no recorded failures)
tests/test_parseur.py ..................                                 [ 52%]
tests/test_thesoitem.py ................                                 [100%]

> INTERNALERROR> Traceback (most recent call last):
> INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/main.py", line 103, in wrap_session
> INTERNALERROR>     session.exitstatus = doit(config, session) or 0
> INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/main.py", line 141, in _main
> INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
> INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
> INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
> INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
> INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
> INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
> INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
> INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/callers.py", line 196, in _multicall
> INTERNALERROR>     gen.send(outcome)
> INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pytest_cov/plugin.py", line 239, in pytest_runtestloop
> INTERNALERROR>     self.cov_total = self.cov_controller.summary(self.cov_report)
> INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pytest_cov/engine.py", line 115, in summary
> INTERNALERROR>     total = self.cov.html_report(ignore_errors=True, directory=self.cov_report['html'])
> INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/control.py", line 1014, in html_report
> INTERNALERROR>     return reporter.report(morfs)
> INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/html.py", line 135, in report
> INTERNALERROR>     self.report_files(self.html_file, morfs, self.config.html_dir)
> INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/report.py", line 75, in report_files
> INTERNALERROR>     report_fn(fr, self.coverage._analyze(fr))
> INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/control.py", line 891, in _analyze
> INTERNALERROR>     return Analysis(self.data, it)
> INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/results.py", line 28, in __init__
> INTERNALERROR>     self._arc_possibilities = sorted(self.file_reporter.arcs())
> INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/python.py", line 165, in arcs
> INTERNALERROR>     return self.parser.arcs()
> INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/parser.py", line 238, in arcs
> INTERNALERROR>     for l1, l2 in self.byte_parser._all_arcs():
> INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/parser.py", line 624, in _all_arcs
> INTERNALERROR>     arcs.update(bp._arcs())
> INTERNALERROR>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/parser.py", line 590, in _arcs
> INTERNALERROR>     next_chunk = byte_chunks[ex]
> INTERNALERROR> KeyError: 32055
```
I really don't have any idea, what to do whith that. Does it come from travis or pytest-cov, I don't know.

pytest.ini
``` ini
testpaths = tests
addopts = --last-failed --exitfirst 
python_paths = .
```

**Comment by blueyed** [comment] 2018-04-02 00:07
Looks like an issue with coveragepy itself.
Make sure to use the latest coveragepy (cannot be seen from your output) - and maybe also upgrade Python itself to 3.6.4.

Side note: maybe pytest-cov could add the coveragepy version to the "plugins:" output?

**Comment by blueyed** [comment] 2018-04-02 00:07
Can you reproduce it locally?

**Comment by jgirardet** [comment] 2018-04-02 21:47
no I can't. I have 3.6.4 locally and it's ok.
I will try some others thing. I tell you if I have  something new

**Comment by bitprophet** [comment] 2018-04-16 23:56
I can confirm this appears to be something to do with coverage.py as I had identical symptoms. Was only under Python 3.6(.1), Python 2.7 was fine. Reproducible locally as well as on Travis.

Example of full broken travis build: https://travis-ci.org/pyinvoke/invoke/jobs/367417412

[Upgrading coverage and related dependencies](https://github.com/pyinvoke/invoke/commit/7b9d092a6a5d69e2608a4be3f2c6800f89f2a0de) appears to fix the issue for me locally as well as on Travis: https://travis-ci.org/pyinvoke/invoke/jobs/367423559

(of note, you can see I was specifically on coverage 3.7.1 and bumping to latest, 4.5.x, fixed. No idea where between those versions the fix actually landed of course!)

**Closed** 2018-06-03 22:46 UTC
