### ISSUE TITLE
pytest-cov makes test fail by putting a temporary file into cwd

### ISSUE THREAD

**Issue by ThomasWaldmann** [pytest-dev/pytest-cov#77] opened 2015-08-08 01:10 UTC
i have tests that check if some specific files have been extracted into cwd.
they fail when using pytest-cov because some .coverage* file gets created there.

is there any way to avoid this?

**Comment by ionelmc** [comment] 2015-08-08 12:53
Have you tried to set something like this in `.coveragerc`?
```
[run]
data_file = /tmp/.coverage
```

**Comment by ThomasWaldmann** [comment] 2015-08-08 13:28
Thanks for the pointer, I tried it:

Still getting this failing test:

>    AssertionError: Lists differ: ['.coverage.testing-worker-lin... != ['file2']

Hmm, maybe this is not a temporary file of coverage, but a lock/pid file of pytest-cov?

**Comment by ionelmc** [comment] 2015-08-08 13:35
Strange. Are you using xdist? That file name appears to be suffixed from [here](https://github.com/pytest-dev/pytest-cov/blob/master/src/pytest_cov/engine.py#L163)

**Comment by ThomasWaldmann** [comment] 2015-08-08 13:42
Well, not by myself / not knowingly, but the tests run on travis-ci.org and they somehow have 1 worker per test environment.

**Comment by ionelmc** [comment] 2015-08-08 13:53
Can you post a link to the build?

On Saturday, August 8, 2015, TW <notifications@github.com> wrote:

> Well, not by myself / not knowingly, but the tests run on travis-ci.org
> and they somehow have 1 worker per test environment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pytest-dev/pytest-cov/issues/77#issuecomment-128982367>
> .
>


-- 

Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by ThomasWaldmann** [comment] 2015-08-08 13:55
https://travis-ci.org/borgbackup/borg/builds/74694517

**Comment by ThomasWaldmann** [comment] 2015-08-08 14:22
https://travis-ci.org/borgbackup/borg/builds/74696354  < hah! was just some vague feeling, that I maybe should try <2.0.0 - and it works now! :)

**Comment by ionelmc** [comment] 2015-08-08 23:27
Having a hard time figuring out how the reproduce your issue. IOW, `data_file` works as expected for me (going to add a test for this soon).

Do you do anything special for coverage configuration (besides having a `.coveragerc`)?

**Comment by ThomasWaldmann** [comment] 2015-08-09 10:22
Well, the test fail issue just went away as soon as I put <2.0.0 in my requirements file.
So it seems it is not creating this file there any more.
I tried with data_file before, but somehow I couldn't solve with that. Part of the issue is that maybe codecov expects the result file to be .coverage in the toplevel dir of the project.

**Comment by ionelmc** [comment] 2015-08-09 14:22
I've managed to get your project to work as expected, see:
https://travis-ci.org/ionelmc/borg/jobs/74795190

Diff: https://github.com/borgbackup/borg/compare/master...ionelmc:master

The esential parts:

* `data_file` and perhaps `parallel`(not sure if parallel changes anything
but you should have it anyway)
* --cov-config because you seems to do weird stuff in your tests wrt the
current directory and that gets pytest-cov confused

I think the real bug here is that pytest-cov forgets about the .coveragerc
if you change the cwd. I'll investigate more later, but you have a solution
above right now :-)




Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by ionelmc** [comment] 2015-10-01 22:33
The cwd change issue is getting fixed in https://github.com/pytest-dev/pytest-cov/pull/95 if you wanna give it a try.

**Closed** 2015-10-02 18:31 UTC
Labels: bug
