### ISSUE TITLE
GitHub Actions failures on Python 3.8 and 3.9 on pytest81-xdist350-coverage74 (windows)

### ISSUE THREAD

**Issue by cclauss** [pytest-dev/pytest-cov#634] opened 2024-03-17 23:31 UTC
I am unsure how to fix these failing GitHub Actions tests on Windows:
1. py38-pytest81-xdist350-coverage74 (windows)
2. py39-pytest81-xdist350-coverage74 (windows)
3. pypy38-pytest81-xdist350-coverage74 (windows)
4. pypy39-pytest81-xdist350-coverage74 (windows)

**Comment by ionelmc** [comment] 2024-03-18 10:52
Should be fixed now. Turns out they were regressions.

**Closed by ionelmc** 2024-03-18 10:52 UTC
